name: market_movers
version: "1.0.0"
config-version: 2

profile: market_movers

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  market_movers:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  market_movers:
    watchlist:
      +column_types:
        is_holding: boolean
        is_benchmark: boolean
